// Tour frame-sequence manifest (section 05 walkthrough). Frames generated by
// `npm run frames` (scripts/build-frames.sh → FFmpeg, FPS=10). 181 frames over the
// overlay scrub. Desktop 1920w, mobile 1080w. First frame = poster (reduced-motion /
// decode-failure fallback).
// 154 desktop / 132 mobile frames, extracted at 14/12fps from the NEW 24fps-native Seedance
// videos (facade→terrace→water, 11s master). Dense sampling of real 24fps motion = smooth scrub
// (the old 181 frames came from 10fps-downsampled source → choppy/repeating; fixed).
export const TOUR_FRAME_COUNT = 154;

export const pad4 = (n: number) => String(n).padStart(4, "0");

export function tourFramePath(set: "desktop" | "mobile", index1based: number): string {
  return `/frames/tour/${set}/${pad4(index1based)}.webp`;
}

// Poster = first frame (the courtyard arrival) and last = golden-hour water climax.
export const TOUR_POSTER = {
  desktop: tourFramePath("desktop", 1),
  mobile: tourFramePath("mobile", 1),
};
export const TOUR_CLIMAX = {
  desktop: tourFramePath("desktop", TOUR_FRAME_COUNT),
  mobile: tourFramePath("mobile", TOUR_FRAME_COUNT),
};

// Micro-captions on key beats (fade in/out by scrub progress). Derived from the 3 scenes:
// arrival (0–48%), living (48–72%), water (72–100%). Positions are progress fractions.
export const TOUR_CAPTIONS = [
  { at: 0.06, until: 0.2, text: "Двір" },
  { at: 0.52, until: 0.66, text: "Вітальня" },
  { at: 0.82, until: 0.98, text: "Перша лінія до берега" },
] as const;
